import express from 'express';
import { authenticateToken } from '../middleware/auth.js';
import { findMatchingAnswer } from '../services/matchingService.js';
import { generateGeminiResponse } from '../services/geminiService.js';

const router = express.Router();

// Send message and get response
router.post('/message', authenticateToken, async (req, res) => {
    try {
        const { message } = req.body;
        const userId = req.user.id;

        if (!message || message.trim().length === 0) {
            return res.status(400).json({ error: 'Message is required' });
        }

        // Step 1: Try to find matching answer from user's Q&A pairs
        const matchedQA = await findMatchingAnswer(userId, message);

        if (matchedQA) {
            // Found a match in database
            return res.json({
                question: message,
                answer: matchedQA.answer,
                source: 'database',
                matchScore: matchedQA.matchScore,
                matchedQuestion: matchedQA.question
            });
        }

        // Step 2: No match found, use Gemini AI
        const geminiResponse = await generateGeminiResponse(message);

        res.json({
            question: message,
            answer: geminiResponse.answer,
            source: geminiResponse.source,
            note: 'No matching answer found in your Q&A database. Response generated by AI.'
        });
    } catch (error) {
        console.error('Chat error:', error);
        res.status(500).json({ error: 'Failed to process message' });
    }
});

export default router;
